### ISSUE TITLE
Hackintosh inicia e hiberna automaticamente

### ISSUE THREAD

**Issue by marcos-alexandre82** [aspadeto/Inspiron-14-5480_MacOS#1]
Olá, parabéns pela excelente documentação!

Possuo um notebook do mesmo modelo e quando início o meu Hackintosh, antes de carregar totalmente o sistema (na "tela da maçã") a tela escurece uns 90% permanecendo assim na tela de login. 

Nesta tela, por sua vez, o mouse/trackpad não funciona e uns 20/25 segundos depois ele entra sozinho em modo de repouso. Ao pressionar qualquer tecla ele sai do modo de repouso e o brilho de tela está normal e o mouse funcionando perfeitamente.

Notei também que isso só ocorre quando não tenho nenhum monitor externo conectado, porém, com os monitores externos conectados (utilizo dois, como saídas VGA: um com adaptador HDMI/VGA e outro com adaptador Type-C/VGA) a tela do notebook permanece desligada e o trackpad sem funcionar.

O que tenho feito é:
Ligar o notebook com os cabos dos monitores desconectados, aguardar ele fazer o processo de repouso, pressionar uma tecla para ele voltar a ativar, conectar os cabos dos monitores e assim poder utilizá-lo normalmente.

Você passou por algo semelhante ou consegue me ajudar a resolver este problema?

Cheguei a fazer um downgrade na BIOS para deixar na versão 2.2.0 mas o problema persistiu.

Estou usando o Mojave 10.14.6

Obrigado :)

**Comment by aspadeto** [comment]
Desculpe-me pela demora em ver sua mensagem. 
O problema ainda persiste? Eu já passei por comportamento parecido com meu hackintosh, mas recentemente ele está funcionando 100%.
Por favor, verifique se as configurações e kexts que você está usando estão atualizadas.
Aloisio

**Comment by marcos-alexandre82** [comment]
Imagina, tranquilo!

Então, atualmente ele não tem mais feito este problema de escurecer a tela, mas o trackpad só funciona depois de um tempo que eu "fico mexendo" nele (uns 2 minutos). Isso mesmo se o computador já estiver à horas ligado (uso um mouse sem fio).

Agora, a hibernação não funciona corretamente, pois depois de um tempo hibernando ele desperta sozinho ;(

Não sei se trabalha com desenvolvimento, mas por vezes tenho notado que a velocidade de rastreamento do mouse fica bem lenta (alguns picos de consumo do processador) enquanto estou com várias abas do Firefox ou Chrome abertas e editando alguns arquivos, principalmente com o FileZilla conectado à eles. E o envio das alterações tem um delay de uns 10 segundos (especificamente, estou trabalhando em um projeto que a única forma de edição é por SFTP, então isso tem um atraso significativo no final de algumas horas). 

Já percebeu algo semelhante ao problemas acima?

Estou com a última versão da Bios, Catalina e Kexts.

Abraço!

**Comment by aspadeto** [comment]
Rapaz, eu uso meu note para desenvolvimento também, mas não percebi nada disso.
Você colocou um SSD no seu equipamento ou ele ainda tem o SO instalado no HD SATA?

**Comment by marcos-alexandre82** [comment]
SSD NVME Samsung 970 Plus 256GB com dual boot, sendo instalado o macOS primeiro. Uso o HD dele apenas para salvar arquivos e com uma partição com o Linux Mint.

**Comment by aspadeto** [comment]
Comentei sobre o uso com o HD pois antes de instalar o NVME também percebi certa lentidão. Depois do NVME ficou liso demais, mas eu ainda uso o Mojave. 
Vou fechar a issue. Se você precisar de alguma outra coisa, abra outra.
