### ISSUE TITLE
CATALINA

### ISSUE THREAD

**Issue by menaguilherme** [aspadeto/Inspiron-14-5480_MacOS#2]
Olá, tudo bem?

Muito obrigado pelo seu guia, me ajudou bastante!

Uma dúvida, você chegou a atualizar para o catalina? Se sim, o wifi ainda funciona?

Eu instalei o Catalina e usei o tplink w725 e logo depois comprei a mesma placa wifi que a sua, mas não consegui ativar ela de maneira alguma.

Mais uma vez, muito obrigado pela documentação.

Abraço!

**Comment by luancschmitz** [comment]
Olá Guilherme como vai. Também estou acompanhando esse post, pelo que vi tem uma outra placa que  funcionaria no catalina que seria a "BCM94360NG". Encontrei ela no seguinte link:
https://encurtador.com.br/glwGU
Mas atualmente estou utilizando um dongle Tp-Link TL-WN725N para o wifi e um "Orico bta-403" para o bluetooth.

**Comment by aspadeto** [comment]
Não constumo atualizar o MacOS em um hackintosh a não que seja de fato importante, como pode ser o caso de quem usa o XCode, que não é o meu caso. Enfim, permaneço no Mojave até hoje.

De qualquer forma, minha instalação passou a dar alguns problemas quando fiz o update da BIOS.
Qual a versão da Bios que você está usando? Se atualizou fez o patch do DSDT novamente?

Att.

**Comment by aspadeto** [comment]
Possivelmente alguma correção como a do post abaixo pode resolver o seu problema:
https://www.tonymacx86.com/threads/solved-dell-dw1560-dw1830-wifi-bt-issue-on-xps9350.230858/
